/**
 * populationNormStats.ts
 *
 * Auto-generated from configs/population_norm_stats.json — do not edit manually.
 *
 * Population-level mean and std for each sensor column used by the DBN.
 * These values are baked in at build time so Metro bundler does not need
 * access to the configs/ directory (which lives outside the mobile source tree).
 *
 * Used by sensor collectors to compute population z-scores for discretization.
 */

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ColStats {
  mean: number;
  std:  number;
}

// ── Population norm stats ─────────────────────────────────────────────────────

/**
 * Population z-score parameters for all sensor columns handled by the
 * screen-usage and communication collectors.
 * source: configs/population_norm_stats.json (generated by DBN training pipeline)
 */
export const POPULATION_NORM_STATS: Record<string, ColStats> = {
  screen_time_window_minutes:         { mean: 12.466321253962285,  std: 22.27547756840327  },
  dark_window_minutes:                { mean: 17.571873418636592,  std: 25.74409961782152  },
  unlocked_window_minutes:            { mean: 21.758115196177492,  std: 27.13827494303937  },
  yesterday_nighttime_screen_minutes: { mean: 119.40909046068856,  std: 126.40987399180541  },
  prev_day_total_screen_time_minutes: { mean: 258.1407886110331,  std: 284.92391695348164  },
  call_count:                         { mean: 0.09079012171955252,  std: 0.5567267988463052  },
  call_duration_total:                { mean: 9.019475128403574,  std: 108.52925211825396  },
  sms_count:                          { mean: 0.254049109969746,  std: 1.8929315889016747  },
  prev_day_call_count:                { mean: 1.7134026411913459,  std: 3.8699594719711734  },
  prev_day_call_duration_total:       { mean: 173.10087103118855,  std: 685.6392793231324  },
  prev_day_sms_count:                 { mean: 5.0396178701882555,  std: 17.05770427237021  },
  avg_running_tasks_window:           { mean: 0.9753377608160197,  std: 0.40938884521985386  },
  prev_day_avg_running_tasks:         { mean: 1.0289556994232896,  std: 0.3103941468442777  },
  prev_day_peak_running_tasks:        { mean: 3.4799325463743678,  std: 3.271526503263356  },
  hourly_steps:                       { mean: 423.977075794831,  std: 752.7561684653015  },
  prev_day_steps:                     { mean: 8296.71866577413,  std: 5464.194043980762  },
  prev_night_resting_hr:              { mean: 66.26872667989332,  std: 7.230833493718208  },
  prev_night_temperature:             { mean: 33.77112033162092,  std: 0.9052798365412219  },
};

// ── Shared discretization helper ──────────────────────────────────────────────

/**
 * Classify `value` into a named state using an ordered list of bin edges.
 *
 * Matches pandas pd.cut(right=True, include_lowest=True):
 *   bins = (-inf, binEdges[0]], (binEdges[0], binEdges[1]], ..., (binEdges[last], +inf)
 *
 * For population z-score cols the bin_edges are in z-score space.
 * For clinical-threshold cols (activity) the bin_edges are in ratio space.
 *
 * @param value       - the value to classify (z-score or raw ratio)
 * @param binEdges    - sorted ascending boundary values (length = stateLabels.length - 1)
 * @param stateLabels - state names, one more than binEdges
 * @returns           the matched state label
 */
export function discretizeByEdges(
  value:       number,
  binEdges:    number[],
  stateLabels: string[],
): string {
  for (let i = 0; i < binEdges.length; i++) {
    if (value <= binEdges[i]) return stateLabels[i];
  }
  return stateLabels[stateLabels.length - 1];
}
