/**
 * NLU layer — on-device NER using Llama 3.2-1B-Instruct (Q4_K_M).
 *
 * Three-level routing cascade (L1 > L2 > L3):
 *   L1 — text matches a specific item-column question (column-question-map.json)
 *   L2 — text matches a composite/direct source-column description (source-column-descriptions.json)
 *   L3 — direct node-state assignment (feature-node-config.json state labels)
 *
 * Indirect effects (e.g. "drank coffee") are not extracted here — they go to
 * the unmatched vector index for the ReAct agent (Gemma 4B) to handle at
 * insight time.
 *
 * Usage:
 *   await initNlu('/absolute/path/to/Llama-3.2-1B-Instruct.Q4_K_M.gguf');
 *   await warmupNlu();   // call in background at startup — caches system prompt KV
 *   const result = await runNer(db, "I haven't been sleeping well this week");
 *
 * column-question-map.json is generated by:
 *   python -m codebase.backend.export_column_question_map
 */

import type { DB } from '@op-engineering/op-sqlite';
import { initLlama, type LlamaContext } from 'llama.rn';
import * as chrono from 'chrono-node';

import nodeConfig        from '../assets/feature-node-config.json';
import columnQuestionMap from '../assets/column-question-map.json';
import sourceColDescs    from '../assets/source-column-descriptions.json';
import { STALENESS_DAYS } from './evidenceLayer';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface NluEntity {
  // Exactly one of original_column / source_column is set, or both absent (L3)
  original_column?:  string;         // L1: specific item col (e.g. 'phq_interest')
  source_column?:    string;         // L2: composite or direct col (e.g. 'phq_total')
  node_name:         string;         // validated DBN node
  node_value:        string | null;  // validated state, or null for L1/L2
  raw_value?:        number;         // numeric score before discretization (L1/L2)
  confidence:        number;         // [0, 1]
  raw_text:          string;         // exact user phrase
  summary_text:      string;         // compressed factual note for semantic search
  report_scope?:     'today' | 'week' | 'daily';
  report_date_str?:  string;         // YYYY-MM-DD resolved from raw_date_text
  raw_date_text?:    string;         // exact phrase user used ("last Tuesday", "in March")
}

export interface NluResult {
  entities:   NluEntity[];
  unmatched:  string[];   // segments with no L1/L2/L3 match → ReAct agent handles
  topics:     string[];   // per-segment NER-derived topic keywords; walk-back fills gaps
  raw_output: string;
}

export interface IntentResult {
  hasReport:         boolean;  // message contains personal health info to update
  hasQuery:          boolean;  // asks about user's own health state
  hasTrendQuery:     boolean;  // asks about trends/history/changes over time; only true when hasQuery is also true
  isSocial:          boolean;  // ONLY social — no health content; mutually exclusive with others
  isThirdPartyQuery: boolean;  // question about someone else's health
  queryNodes:        string[]; // validated DBN node names queried (max 10)
}

// ── Schema tables (built once at module load) ─────────────────────────────────

interface NodeConfigEntry {
  state_labels?:       string[];
  description?:        string;
  self_report?:        boolean;
  temporal?:           boolean;
  source_column_bins?: Record<string, unknown>;
}
interface ColumnEntry {
  c:      string;
  n:      string;
  q:      string;
  opts?:  { v: number; l: string }[];
  range?: { min: number; max: number; unit: string };
}

const _nodes  = (nodeConfig as any).nodes as Record<string, NodeConfigEntry>;
const _cqMap  = columnQuestionMap as Record<string, ColumnEntry>;
const _srcDesc = sourceColDescs   as Record<string, string>;

// NODE_SCHEMA — self_report nodes only
interface NodeSchemaEntry { states: string[]; temporal: boolean; }
const NODE_SCHEMA: Record<string, NodeSchemaEntry> = (() => {
  const s: Record<string, NodeSchemaEntry> = {};
  for (const [name, node] of Object.entries(_nodes)) {
    if (!node.self_report) continue;
    const states = node.state_labels ?? [];
    if (states.length) s[name] = { states, temporal: node.temporal ?? true };
  }
  return s;
})();

// SOURCE_COL_TO_NODE — reverse map from source_column_bins keys → node_name
const SOURCE_COL_TO_NODE: Record<string, string> = (() => {
  const m: Record<string, string> = {};
  for (const [name, node] of Object.entries(_nodes)) {
    if (!node.self_report) continue;
    for (const col of Object.keys(node.source_column_bins ?? {})) m[col] = name;
    // node name itself may also be a composite column name (e.g. pain_level)
    m[name] = name;
  }
  return m;
})();

// COMPOSITE_ITEM_COUNT — items per source column for L1 confidence = 1/n
const COMPOSITE_ITEM_COUNT: Record<string, number> = (() => {
  const counts: Record<string, number> = {};
  for (const entry of Object.values(_cqMap)) {
    counts[entry.c] = (counts[entry.c] ?? 0) + 1;
  }
  return counts;
})();

// SENSORLESS_COL_BINS — discretization config per source column (self_report nodes only)
interface ColBinConfig {
  method:       string;
  thresholds?:  number[];          // clinical: raw-value boundaries
  bin_edges?:   number[];          // kmeans: z-score space — not usable without user history
  state_labels: string[];
  state_map?:   Record<string, string>; // col-label → node-label remapping (for mismatched cardinality)
  value_map?:   Record<string, string>; // numeric option code → intermediate label (applied before state_map)
  is_composite?: boolean;              // true only for summed instruments (PHQ-9, GAD-7); guards composite early-return
}
const SENSORLESS_COL_BINS: Record<string, ColBinConfig> = (() => {
  const m: Record<string, ColBinConfig> = {};
  for (const node of Object.values(_nodes)) {
    if (!node.self_report) continue;
    for (const [col, raw] of Object.entries(node.source_column_bins ?? {})) {
      const b = raw as Record<string, unknown>;
      m[col] = {
        method:       typeof b.method === 'string' ? b.method : 'kmeans',
        thresholds:   Array.isArray(b.thresholds)  ? (b.thresholds  as number[]) : undefined,
        bin_edges:    Array.isArray(b.bin_edges)    ? (b.bin_edges   as number[]) : undefined,
        state_labels: Array.isArray(b.state_labels) ? (b.state_labels as string[]) : [],
        state_map:    (b.state_map && typeof b.state_map === 'object' && !Array.isArray(b.state_map))
          ? (b.state_map as Record<string, string>)
          : undefined,
        value_map:    (b.value_map && typeof b.value_map === 'object' && !Array.isArray(b.value_map))
          ? (b.value_map as Record<string, string>)
          : undefined,
        is_composite: typeof b.is_composite === 'boolean' ? b.is_composite : undefined,
      };
    }
  }
  return m;
})();

// ── Prompt sections (static strings, built once) ──────────────────────────────

function firstClause(desc: string): string {
  for (const sep of ['. ', ' — ', ' – ']) {
    const idx = desc.indexOf(sep, 15);
    if (idx !== -1) return desc.slice(0, idx).trim();
  }
  return desc.trim();
}

const L1_PROMPT = JSON.stringify(_cqMap);

const L2_PROMPT = JSON.stringify(
  Object.fromEntries(
    Object.entries(_srcDesc)
      .filter(([col]) => !col.startsWith('_'))
      .map(([col, desc]) => [
        col,
        { d: firstClause(desc as string), n: SOURCE_COL_TO_NODE[col] ?? null },
      ]),
  ),
);

const L3_PROMPT = JSON.stringify(
  Object.fromEntries(Object.entries(NODE_SCHEMA).map(([n, e]) => [n, e.states])),
);

// ── System prompt ─────────────────────────────────────────────────────────────

// Mode-based confidence gates. After L1 gate passes, confidence overridden to 1/COMPOSITE_ITEM_COUNT.
const CONFIDENCE_GATES = {
  glance:  { l1: 0.65, l2: 0.6, l3: 0.5 },
  reflect: { l1: 0.8,  l2: 0.8, l3: 0.8 },
} as const;

const SYSTEM_PROMPT = `You are a health data extraction assistant. One message may produce multiple entities. Return ONLY a valid JSON array — no prose, no markdown fences. Return [] if nothing matches.
If the input is a question, a request to know, or expresses curiosity rather than reporting a personal health state, return [].

## Output fields
Each entity:
- original_column : L1 item column name, or null
- source_column   : L2 composite/instrument column, or null
- node_name       : DBN node name (required)
- node_value      : valid state string (L3 only); null for L1/L2
- raw_value       : numeric option code or score; null if vague
- confidence      : your certainty this match is correct [0.0-1.0]
- report_scope    : "today" | "week" | "daily"
- raw_date_text   : exact time phrase user used, or null
- raw_text        : exact phrase from user that produced this entity
- summary_text    : compressed fact — keep quantities, symptoms, durations; drop articles, filler, metadata

report_scope: "today"=about today or a specific past day; "week"=past week or recent period ("lately", "recently", "this week", "been"); "daily"=recurring habit or stable trait ("usually", "normally", "every day", "I smoke", "I drink").
raw_date_text: copy exact phrase for specific past times ("yesterday", "last Tuesday", "3 days ago"); null for habits/ongoing ("I smoke daily").
summary_text: factual compression of raw_text only — no node names, column names, or added context.

## Routing rules
1. L1 — item-level (preferred):
   - Use when text directly and semantically matches a question label (q field) — paraphrase OK; inference and implied downstream effects not allowed
   - Set: original_column=<col>, source_column=null, node_value=null
   - raw_value: pick opts v value matching user's intensity/frequency; use range for numeric; null if vague
   - Multi-match: produce one entity per matching original_column; same or different source columns (c) both valid

2. L2 — instrument/score:
   - Use ONLY when user explicitly names an instrument or score (e.g. "PHQ-9") AND no L1 column covers the same claim
   - Set: original_column=null, source_column=<col>, node_value=null, raw_value=<score>

3. L3 — node-level fallback:
   - Use only when no L1 or L2 match applies
   - Set: original_column=null, source_column=null, node_value=<valid state from L3 map>
   - confidence ≥ 0.8 only when the state label clearly and directly matches the phrase; use 0.6–0.79 for less certain matches
   - Multiple L1 entities from the same phrase are allowed when multiple columns match. L3 may additionally fire alongside L1 only when a separate node dimension is clearly present in the phrase (not inferred or implied).

Constraints: never set both original_column and source_column non-null; never set node_value when a column field is non-null.

## Reference maps
L1 — item columns {original_column:{c:source_col,n:node,q:question}}:
${L1_PROMPT}

L2 — source columns {source_col:{d:description,n:node}}:
${L2_PROMPT}

L3 — node states {node:[valid_states]}:
${L3_PROMPT}

## Examples
User: "I barely have any interest in things I used to enjoy"
[{"original_column":"phq_interest","source_column":null,"node_name":"depression","node_value":null,"raw_value":3,"report_scope":"week","raw_date_text":null,"confidence":0.9,"raw_text":"barely have any interest in things I used to enjoy","summary_text":"barely interested in previously enjoyable things"},{"original_column":"DPQ010","source_column":null,"node_name":"depression","node_value":null,"raw_value":3,"report_scope":"week","raw_date_text":null,"confidence":0.9,"raw_text":"barely have any interest in things I used to enjoy","summary_text":"barely interested in previously enjoyable things"}]

User: "My PHQ-9 score was 15 last week"
[{"original_column":null,"source_column":"phq_total","node_name":"depression","node_value":null,"raw_value":15,"report_scope":"week","raw_date_text":"last week","confidence":0.9,"raw_text":"PHQ-9 score was 15 last week","summary_text":"PHQ-9 score 15, past week"}]

User: "I've been feeling moderately depressed this past week"
[{"original_column":"phq_depressed","source_column":null,"node_name":"depression","node_value":null,"raw_value":2,"report_scope":"week","raw_date_text":null,"confidence":0.9,"raw_text":"feeling moderately depressed this past week","summary_text":"moderately depressed, past week"},{"original_column":"DPQ020","source_column":null,"node_name":"depression","node_value":null,"raw_value":2,"report_scope":"week","raw_date_text":null,"confidence":0.9,"raw_text":"feeling moderately depressed this past week","summary_text":"moderately depressed, past week"},{"original_column":"n_depressed","source_column":null,"node_name":"neuroticism","node_value":null,"raw_value":2,"report_scope":"week","raw_date_text":null,"confidence":0.85,"raw_text":"feeling moderately depressed this past week","summary_text":"moderately depressed, past week"}]

User: "I smoke about a pack of cigarettes every day"
[{"original_column":"SMQ040","source_column":null,"node_name":"smoking","node_value":null,"raw_value":1,"report_scope":"daily","raw_date_text":null,"confidence":1.0,"raw_text":"smoke about a pack of cigarettes every day","summary_text":"smokes pack daily"}]

User: "I had chest pain yesterday"
[{"original_column":"CDQ001","source_column":null,"node_name":"pain_level","node_value":null,"raw_value":1,"report_scope":"today","raw_date_text":"yesterday","confidence":0.9,"raw_text":"had chest pain yesterday","summary_text":"chest pain yesterday"}]

User: "Stressed about exams and slept only 5 hours last night"
[{"original_column":"stress_ema_level","source_column":null,"node_name":"stress_ema","node_value":null,"raw_value":2,"report_scope":"today","raw_date_text":null,"confidence":0.95,"raw_text":"Stressed about exams","summary_text":"stressed about exams"},{"original_column":"prev_day_sleep_ema_hours","source_column":null,"node_name":"sleep_quality","node_value":null,"raw_value":5,"report_scope":"today","raw_date_text":"last night","confidence":1.0,"raw_text":"slept only 5 hours last night","summary_text":"slept 5 hours last night"}]

User: "I slept a lot last night"
[{"original_column":"prev_day_sleep_ema_hours","source_column":null,"node_name":"sleep_quality","node_value":null,"raw_value":null,"report_scope":"today","raw_date_text":"last night","confidence":0.9,"raw_text":"slept a lot last night","summary_text":"slept a lot last night"}]

User: "I've been feeling very lonely lately"
[{"original_column":null,"source_column":null,"node_name":"loneliness","node_value":"high","raw_value":null,"report_scope":"week","raw_date_text":null,"confidence":0.8,"raw_text":"feeling very lonely lately","summary_text":"very lonely, recently"}]

User: "I feel frustrated and anxious today"
[{"original_column":null,"source_column":null,"node_name":"negative_affect","node_value":"moderate_high","raw_value":null,"report_scope":"today","raw_date_text":null,"confidence":0.85,"raw_text":"feel frustrated today","summary_text":"frustrated today"},{"original_column":null,"source_column":null,"node_name":"stress_ema","node_value":"high","raw_value":null,"report_scope":"today","raw_date_text":null,"confidence":0.85,"raw_text":"feel anxious today","summary_text":"anxious today"}]

User: "I feel really tired and drained today"
[{"original_column":null,"source_column":null,"node_name":"mood","node_value":"low","raw_value":null,"report_scope":"today","raw_date_text":null,"confidence":0.8,"raw_text":"feel really tired and drained today","summary_text":"tired and drained today"}]

User: "I am having anxiety right now"
[{"original_column":null,"source_column":null,"node_name":"stress_ema","node_value":"high","raw_value":null,"report_scope":"today","raw_date_text":null,"confidence":0.9,"raw_text":"having anxiety right now","summary_text":"anxiety right now"}]

User: "I had a coffee this morning"
[]

User: "How is my stress today?"
[]

User: "I want to know about my stress"
[]

User: "I usually sleep around 7 hours"
[{"original_column":"prev_day_sleep_ema_hours","source_column":null,"node_name":"sleep_quality","node_value":null,"raw_value":7,"report_scope":"daily","raw_date_text":null,"confidence":0.9,"raw_text":"usually sleep around 7 hours","summary_text":"usually sleeps 7 hours"}]`;

// ── Singleton context ──────────────────────────────────────────────────────────

let _ctx:       LlamaContext | null = null;
let _modelPath: string | null       = null;

/**
 * Load the Llama 3.2-1B model. Call once at app startup.
 * n_ctx=8192: the three-level schema injected into the prompt is ~4800 tokens;
 * remaining headroom covers user messages and generated output.
 */
export function setNluPath(modelPath: string): void {
  _modelPath = modelPath;
}

export async function initNlu(modelPath: string): Promise<void> {
  if (_ctx && _modelPath === modelPath) return;
  if (_ctx) { await _ctx.release(); _ctx = null; }
  _modelPath = modelPath;
  try {
    _ctx = await initLlama({
      model:      modelPath,
      use_mlock:  false,
      n_ctx:      4096,
      n_threads:  4,
      n_parallel: 1,
    });
  } catch (e) {
    throw new Error(`nlu load failed [path=${modelPath}]: ${e instanceof Error ? e.message : String(e)}`);
  }
}

/** Reinitialise from stored path if context was evicted by OS. */
export async function ensureNlu(): Promise<void> {
  if (_ctx) return;
  if (!_modelPath) throw new Error('nlu: initNlu() has not been called — no model path stored');
  await initNlu(_modelPath);
}

/**
 * Pre-process the segmentation prompt so its KV cache is warm before the
 * first real runNer() call. Segmentation always runs first, so warming it
 * (not the NER prompt) is what saves latency on first user message.
 */
export async function warmupNlu(): Promise<void> {
  if (!_ctx) return;
  await _ctx.completion({
    prompt:      buildSegmentPrompt(''),
    n_predict:   1,
    temperature: 0.0,
    stop:        ['<|eot_id|>'],
  });
}

export function isNluReady(): boolean { return _ctx !== null; }

export async function releaseNlu(): Promise<void> {
  if (_ctx) { await _ctx.release(); _ctx = null; }
}

// ── Segmenter ─────────────────────────────────────────────────────────────────

const SEGMENT_SYSTEM_PROMPT = `You split a user's message into individual health statements to record. Return ONLY a valid JSON array of strings — no prose, no markdown fences.

INCLUDE — statements where the user reports their own health state, event, behavior, or experience:
- One segment per separate event, activity, feeling, state, or thing consumed or experienced
- Carry shared time/context ("today", "last night", "this week") into each split segment that lacks its own time reference
- Preserve the user's exact words — only permitted addition: carrying a shared time word from the message
- Single activity described together stays one segment ("went to the gym and worked out hard" → one)
- Linked cause-effect becomes two segments ("tired because of poor sleep" → two)
- Correction/undo phrases stay intact — do not split from their replacement value
- Negated health claims stay intact ("I didn't exercise today" → keep as one segment, do not drop)

EXCLUDE — drop the excluded portion; return [] if nothing is left:
- Questions of any form — direct ("How is my sleep?") or declarative ("I want to know about my stress", "I'm curious about my anxiety", "I wonder if my stress is affecting my sleep", "tell me how I'm doing", "can you check my health")
- Speculation framing ("maybe my anxiety is better", "I imagine I'm quite stressed", "I wonder if...")
- Social greetings ("Hey!", "Hi!", "Good morning!") — drop greeting; keep any health content that follows
- Third-party claims — anything about another person (mom, friend, partner, colleague, they) — drop; keep user's own claims
- Requests for information about the user's own state ("show me my sleep data", "what does my health look like")

Maximum 10 segments per message.

Examples:
User: "Stressed about exams and slept only 5 hours last night"
["Stressed about exams", "slept only 5 hours last night"]

User: "I went out with friends today. I chilled, played cricket and had coffee and some snacks"
["went out with friends today", "chilled today", "played cricket today", "had coffee today", "had some snacks today"]

User: "I feel really anxious and depressed this week"
["I feel really anxious this week", "I feel really depressed this week"]

User: "My PHQ-9 was 15 and I smoke a pack daily and had chest pain yesterday"
["My PHQ-9 was 15", "I smoke a pack daily", "had chest pain yesterday"]

User: "I had a coffee this morning"
["I had a coffee this morning"]

User: "I exercised for an hour and also had 3 beers"
["I exercised for an hour", "had 3 beers"]

User: "I felt tired because I barely slept last night"
["I felt tired", "barely slept last night"]

User: "I went to the gym and worked out hard today"
["I went to the gym and worked out hard today"]

User: "Actually I meant 6 hours sleep, I also feel anxious today"
["Actually I meant 6 hours sleep", "I feel anxious today"]

User: "I didn't exercise today"
["I didn't exercise today"]

User: "What time is it?"
[]

User: "How is my stress today?"
[]

User: "I want to know about my stress"
[]

User: "I'm curious about my anxiety levels"
[]

User: "I wonder if my stress is affecting my sleep"
[]

User: "Good morning!"
[]

User: "Hey! I slept really well last night"
["I slept really well last night"]

User: "I feel exhausted today — how's my sleep looking?"
["I feel exhausted today"]

User: "I slept only 4 hours and I want to see my sleep trend"
["I slept only 4 hours"]

User: "I feel anxious and I'm wondering if that's been getting worse"
["I feel anxious"]

User: "I feel frustrated and tired today. Did a lot of work with no rest. I am having anxiety right now."
["I feel frustrated today", "I feel tired today", "Did a lot of work with no rest today", "I am having anxiety right now"]

User: "My mom has been tired and I've been feeling pretty low too"
["I've been feeling pretty low"]

User: "My friend hasn't been sleeping well lately"
[]

User: "Hi! I feel great today. How am I doing overall?"
["I feel great today"]

User: "I feel better. What does this app do?"
["I feel better"]`;

function buildSegmentPrompt(userText: string): string {
  return (
    `<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n` +
    `${SEGMENT_SYSTEM_PROMPT}<|eot_id|>` +
    `<|start_header_id|>user<|end_header_id|>\n\n` +
    `${userText}<|eot_id|>` +
    `<|start_header_id|>assistant<|end_header_id|>\n\n`
  );
}

function parseSegments(raw: string): { segments: string[]; failed: boolean } {
  const cleaned = raw.replace(/```(?:json)?/g, '').trim();
  const start   = cleaned.indexOf('[');
  const end     = cleaned.lastIndexOf(']');
  if (start === -1 || end === -1 || end < start) return { segments: [], failed: true };
  try {
    const arr     = JSON.parse(cleaned.slice(start, end + 1)) as unknown[];
    const strings = arr.filter((s): s is string => typeof s === 'string' && s.trim().length > 0);
    return { segments: strings, failed: false };
  } catch {
    return { segments: [], failed: true };
  }
}

async function segmentText(userText: string): Promise<string[]> {
  await ensureNlu();
  try {
    const out = await _ctx!.completion({
      prompt:      buildSegmentPrompt(userText),
      n_predict:   200,
      temperature: 0.0,
      stop:        ['<|eot_id|>', '<|end_of_text|>'],
    });
    const { segments, failed } = parseSegments(out.text);
    // failed = JSON parse error → treat full text as one claim (safe fallback)
    // succeeded + empty = SLM found no health content → return [] so NER is skipped
    return failed ? [userText] : segments;
  } catch {
    return [userText];
  }
}

// ── Prompt builder ─────────────────────────────────────────────────────────────

function buildPrompt(userText: string, todayIso: string): string {
  return (
    `<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n` +
    `${SYSTEM_PROMPT}\n\nToday: ${todayIso}<|eot_id|>` +
    `<|start_header_id|>user<|end_header_id|>\n\n` +
    `${userText}<|eot_id|>` +
    `<|start_header_id|>assistant<|end_header_id|>\n\n`
  );
}

// ── Output parser ──────────────────────────────────────────────────────────────

/**
 * Parse and validate JSON entity array from raw model output.
 *
 * L1: original_column must be in _cqMap. Confidence overridden to
 *     1 / COMPOSITE_ITEM_COUNT[source_col] — model value ignored.
 * L2: source_column must resolve to a self_report node. node_value must be null.
 * L3: node_value must be a valid state. confidence >= MIN_CONFIDENCE_L3.
 */
function parseEntities(raw: string, now: Date, mode: 'glance' | 'reflect'): NluEntity[] {
  const gates = CONFIDENCE_GATES[mode];
  const cleaned = raw.replace(/```(?:json)?/g, '').trim();
  const start   = cleaned.indexOf('[');
  const end     = cleaned.lastIndexOf(']');
  if (start === -1 || end === -1 || end < start) return [];

  let parsed: unknown[];
  try { parsed = JSON.parse(cleaned.slice(start, end + 1)) as unknown[]; }
  catch { return []; }

  const result: NluEntity[] = [];

  for (const item of parsed) {
    if (typeof item !== 'object' || item === null) continue;
    const e = item as Record<string, unknown>;

    const origCol  = typeof e.original_column === 'string' ? e.original_column : null;
    const srcCol   = typeof e.source_column   === 'string' ? e.source_column   : null;
    const nodeName = typeof e.node_name       === 'string' ? e.node_name       : null;
    const nodeVal  = typeof e.node_value      === 'string' ? e.node_value      : null;
    const rawVal   = typeof e.raw_value       === 'number' ? e.raw_value       : undefined;
    const rawText  = typeof e.raw_text        === 'string' ? e.raw_text        : null;
    const summary  = typeof e.summary_text    === 'string' ? e.summary_text    : null;
    const confRaw  = typeof e.confidence      === 'number' ? e.confidence      : null;

    if (!nodeName || !rawText || !summary) continue;

    const scope = (['today', 'week', 'daily'] as const).find(s => s === e.report_scope);
    const rawDateText = typeof e.raw_date_text === 'string' ? e.raw_date_text : undefined;
    const reportDateStr = rawDateText
      ? (chrono.parseDate(rawDateText, now)?.toISOString().slice(0, 10) ?? undefined)
      : undefined;

    if (origCol !== null) {
      // ── L1 ────────────────────────────────────────────────────────────────
      const entry = _cqMap[origCol];
      if (!entry || !NODE_SCHEMA[entry.n]) continue;
      if ((confRaw ?? 0) < gates.l1) continue;
      const confidence = 1 / (COMPOSITE_ITEM_COUNT[entry.c] ?? 1);
      result.push({
        original_column: origCol,
        node_name: entry.n, node_value: null, raw_value: rawVal,
        confidence, raw_text: rawText, summary_text: summary,
        report_scope: scope, raw_date_text: rawDateText, report_date_str: reportDateStr,
      });

    } else if (srcCol !== null) {
      // ── L2 ────────────────────────────────────────────────────────────────
      const resolvedNode = SOURCE_COL_TO_NODE[srcCol]
        ?? (_nodes[srcCol]?.self_report ? srcCol : null);
      if (!resolvedNode || !NODE_SCHEMA[resolvedNode]) continue;
      if ((confRaw ?? 0) < gates.l2) continue;
      result.push({
        source_column: srcCol,
        node_name: resolvedNode, node_value: null, raw_value: rawVal,
        confidence: confRaw ?? 0.7,
        raw_text: rawText, summary_text: summary,
        report_scope: scope, raw_date_text: rawDateText, report_date_str: reportDateStr,
      });

    } else {
      // ── L3 ────────────────────────────────────────────────────────────────
      const schema = NODE_SCHEMA[nodeName];
      if (!schema || !nodeVal || !schema.states.includes(nodeVal)) continue;
      const confidence = confRaw ?? 0.5;
      if (confidence < gates.l3) continue;
      result.push({
        node_name: nodeName, node_value: nodeVal, raw_value: rawVal,
        confidence, raw_text: rawText, summary_text: summary,
        report_scope: scope, raw_date_text: rawDateText, report_date_str: reportDateStr,
      });
    }
  }

  return result;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function deduplicateEntities(entities: NluEntity[]): NluEntity[] {
  const seen = new Map<string, NluEntity>();
  for (const ent of entities) {
    const col = ent.original_column ?? ent.source_column ?? ent.node_name;
    const key = `${col}||${ent.report_scope ?? ''}`;
    const existing = seen.get(key);
    if (!existing || ent.confidence > existing.confidence) seen.set(key, ent);
  }
  return [...seen.values()];
}

function toExpiresDate(scope: string | undefined, baseDate: string): string | null {
  if (!scope || scope === 'daily') return null;
  const d = new Date(baseDate + 'T00:00:00'); // local midnight, avoids UTC-minus rollback
  d.setDate(d.getDate() + (scope === 'week' ? 7 : 1));
  return d.toLocaleDateString('sv'); // YYYY-MM-DD local
}

function discretizeClinical(rawVal: number, thresholds: number[], stateLabels: string[]): string | null {
  // thresholds = [min, b1, b2, ..., max]; stateLabels[i] covers [thresholds[i], thresholds[i+1])
  for (let i = 0; i < stateLabels.length - 1; i++) {
    if (rawVal < thresholds[i + 1]) return stateLabels[i];
  }
  return stateLabels[stateLabels.length - 1] ?? null;
}

/**
 * Returns the composite source column (e.g. 'phq_total') for a given item column
 * (e.g. 'phq_sleep'), or the item column itself if no mapping exists.
 * Used by agent.ts completeTurn to pass the correct column to maybeResolveComposite.
 */
export function getCompositeSourceCol(itemCol: string): string {
  return _cqMap[itemCol]?.c ?? itemCol;
}

export function resolveNodeValue(ent: NluEntity): string | null {
  let col: string | null = null;
  if (ent.original_column) {
    const srcCol = _cqMap[ent.original_column]?.c;
    if (!srcCol) return null;
    // Composite instruments (e.g. PHQ-9, GAD-7): item raw_value (0–3) ≠ total score → skip.
    // Guard is now driven by is_composite flag rather than item count, so independent
    // binary questions (pain_level, diabetes_status, etc.) are not blocked.
    const binConf = SENSORLESS_COL_BINS[srcCol];
    if (binConf?.is_composite === true) return null;
    col = srcCol;
  } else if (ent.source_column) {
    col = ent.source_column;
  }

  if (!col) return null;
  const binConf = SENSORLESS_COL_BINS[col];
  if (!binConf) return null;

  const nodeStates = NODE_SCHEMA[ent.node_name]?.states ?? [];

  // Passthrough: raw string IS the node state — apply value_map then state_map if provided
  if (binConf.method === 'passthrough') {
    const rawStr    = typeof ent.raw_value === 'number' ? String(ent.raw_value) : ent.raw_text;
    const afterVMap = binConf.value_map ? (binConf.value_map[rawStr] ?? rawStr) : rawStr;
    const mapped    = binConf.state_map ? (binConf.state_map[afterVMap] ?? afterVMap) : afterVMap;
    return nodeStates.includes(mapped) ? mapped : null;
  }

  // Clinical: if value_map present, apply it first to convert numeric code → label,
  // then either pass straight to state_map (no thresholds) or discretize numerically.
  if (binConf.method === 'clinical') {
    // value_map path: numeric option code → intermediate label → state_map → node state
    if (binConf.value_map && ent.raw_value !== undefined) {
      const rawStr    = String(ent.raw_value);
      const afterVMap = binConf.value_map[rawStr];
      if (afterVMap !== undefined) {
        const mapped = binConf.state_map ? (binConf.state_map[afterVMap] ?? afterVMap) : afterVMap;
        return nodeStates.includes(mapped) ? mapped : null;
      }
    }
    // Threshold path: discretize numeric raw_value, then apply state_map if needed
    if (binConf.thresholds?.length && ent.raw_value !== undefined) {
      const discretized = discretizeClinical(ent.raw_value, binConf.thresholds, binConf.state_labels);
      if (!discretized) return null;
      const mapped = binConf.state_map ? (binConf.state_map[discretized] ?? discretized) : discretized;
      return nodeStates.includes(mapped) ? mapped : null;
    }
  }

  return null;
}

// ── Composite completeness ────────────────────────────────────────────────────

/**
 * After each new L1 item write for a multi-item source column, check whether
 * ≥ 80% of items are now answered within the current turn. If so, compute a
 * partial total score and discretize it, then update node_value on all rows
 * for that (node, turn) with a scaled confidence.
 *
 * Confidence scaling: 0.65 + 0.25 * (answered / total)
 *   4/5 items answered → 0.85;  5/5 → 0.90
 */
export function maybeResolveComposite(db: DB, nodeName: string, sourceCol: string, turnId: string): void {
  const total = COMPOSITE_ITEM_COUNT[sourceCol];
  if (!total || total <= 1) return; // not a composite instrument

  const rows = db.executeSync(
    `SELECT raw_value FROM user_data_sensorless
     WHERE node_name = ? AND turn_id = ? AND is_active = 1
       AND raw_value IS NOT NULL
       AND original_column IN (
         SELECT value FROM json_each(?)
       )`,
    [nodeName, turnId, JSON.stringify(Object.keys(_cqMap).filter(k => _cqMap[k].c === sourceCol))],
  ).rows as { raw_value: number }[];

  const answered = rows.length;
  if (answered === 0 || answered / total < 0.8) return;

  const totalScore = rows.reduce((s, r) => s + Number(r.raw_value), 0);
  const binConf    = SENSORLESS_COL_BINS[sourceCol];
  if (!binConf || binConf.method !== 'clinical' || !binConf.thresholds?.length) return;

  const discretized = discretizeClinical(totalScore, binConf.thresholds, binConf.state_labels);
  if (!discretized) return;

  const nodeStates = NODE_SCHEMA[nodeName]?.states ?? [];
  const mapped     = binConf.state_map ? (binConf.state_map[discretized] ?? discretized) : discretized;
  if (!nodeStates.includes(mapped)) return;

  const confidence = 0.65 + 0.25 * (answered / total);

  db.executeSync(
    `UPDATE user_data_sensorless
     SET node_value = ?, confidence = ?
     WHERE node_name = ? AND turn_id = ? AND is_active = 1
       AND original_column IN (
         SELECT value FROM json_each(?)
       )`,
    [mapped, confidence, nodeName, turnId,
     JSON.stringify(Object.keys(_cqMap).filter(k => _cqMap[k].c === sourceCol))],
  );
}

// ── Public API ─────────────────────────────────────────────────────────────────

/**
 * Run on-device NER on userText, write all valid entities to
 * user_data_sensorless, and return the result.
 * Returns empty entities without throwing if model is not initialised.
 *
 * @param db           - Open SQLite handle (from openDb()).
 * @param userText     - Raw user message.
 * @param questionText - Question the app asked, if any (audit trail).
 */
export async function runNer(
  db:           DB,
  userText:     string,
  questionText: string = '',
  turnId:       string = '',
  mode:         'glance' | 'reflect' = 'reflect',
  sessionId:    string = '',
): Promise<NluResult> {
  await ensureNlu();

  const now      = new Date();
  const todayIso = now.toISOString().slice(0, 10);
  const ts       = now.toISOString().replace('T', ' ').slice(0, 19);

  // Pass 1: split into individual health claims
  const segments = await segmentText(userText);
  if (segments.length === 0) return { entities: [], unmatched: [], topics: [], raw_output: '' };

  // Pass 2: NER on each segment — each call targets one claim → reliable output
  const rawParts:    string[]    = [];
  const allEntities: NluEntity[] = [];
  const unmatched:   string[]    = [];
  const topicParts:  string[]    = [];

  // Lazy-loaded fallback topic from most recent stored message (walk-back for no-entity segments)
  let fallbackTopic: string | null = null;
  function getFallbackTopic(): string {
    if (fallbackTopic !== null) return fallbackTopic;
    if (!sessionId) return (fallbackTopic = '');
    const row = db.executeSync(
      `SELECT topic FROM chat_messages
       WHERE session_id = ? AND topic IS NOT NULL AND topic != '' AND is_active = 1
       ORDER BY created_at DESC LIMIT 1`,
      [sessionId],
    ).rows[0] as { topic: string } | undefined;
    return (fallbackTopic = row?.topic ?? '');
  }

  for (const segment of segments) {
    let raw: string;
    try {
      const out = await _ctx!.completion({
        prompt:      buildPrompt(segment, todayIso),
        n_predict:   512,
        temperature: 0.1,
        top_p:       0.9,
        stop:        ['<|eot_id|>', '<|end_of_text|>'],
      });
      raw = out.text;
    } catch {
      unmatched.push(segment);
      const fb = getFallbackTopic();
      if (fb) topicParts.push(fb);
      continue;
    }
    rawParts.push(raw);
    const parsed = parseEntities(raw, now, mode);
    if (parsed.length === 0) {
      unmatched.push(segment);
      // No NER match — use most recent stored topic as this segment's topic
      const fb = getFallbackTopic();
      if (fb) topicParts.push(fb);
    } else {
      allEntities.push(...parsed);
      // Topic = summary_text of each entity extracted from this segment
      const segTopic = parsed.map(e => e.summary_text).join(', ');
      topicParts.push(segTopic);
    }
  }

  const entities = deduplicateEntities(allEntities);

  for (const ent of entities) {
    const schema      = NODE_SCHEMA[ent.node_name]!;
    const reportDate  = ent.report_date_str ?? todayIso;
    const expiresDate = toExpiresDate(ent.report_scope, reportDate);
    const mergeMode   = ent.original_column ? 'scale' : 'latest';

    let proactiveSuppressedUntil: string | null = null;
    if (ent.original_column) {
      if (expiresDate) {
        proactiveSuppressedUntil = expiresDate;
      } else {
        const staleDays = STALENESS_DAYS[ent.node_name];
        if (staleDays) {
          const d = new Date(now);
          d.setDate(d.getDate() + staleDays);
          proactiveSuppressedUntil = d.toISOString().slice(0, 10);
        }
      }
    }

    const resolvedNodeValue = ent.node_value ?? resolveNodeValue(ent);

    db.executeSync(
      `INSERT INTO user_data_sensorless
         (timestamp, node_name, original_column, source_column,
          question_text, raw_text, node_value, raw_value,
          confidence, data_source, merge_mode, temporal_flag,
          report_date, expires_date, summary_text, turn_id,
          proactive_suppressed_until, was_proactive, answered)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, 1)`,
      [
        ts,
        ent.node_name,
        ent.original_column ?? null,
        ent.source_column   ?? null,
        questionText        || null,
        userText,
        resolvedNodeValue   ?? null,
        ent.raw_value       ?? null,
        ent.confidence,
        'self_report',
        mergeMode,
        schema.temporal ? 'decaying' : 'persistent',
        reportDate,
        expiresDate,
        ent.summary_text,
        turnId              || null,
        proactiveSuppressedUntil,
      ],
    );

    // For L1 entities belonging to multi-item composites, check if ≥80% is now answered
    if (ent.original_column && turnId) {
      const srcCol = _cqMap[ent.original_column]?.c;
      if (srcCol) maybeResolveComposite(db, ent.node_name, srcCol, turnId);
    }
  }

  // Deduplicate topic parts while preserving order
  const seen = new Set<string>();
  const topics = topicParts.filter(t => { if (seen.has(t)) return false; seen.add(t); return true; });

  return { entities, unmatched, topics, raw_output: rawParts.join('\n---\n') };
}

// ── Intent classification ─────────────────────────────────────────────────────

const CLASSIFY_INTENT_SYSTEM_PROMPT = `You are a JSON intent classifier for a personal health app. Output ONLY valid JSON. No prose.

SCHEMA:
{"hasReport":bool,"hasQuery":bool,"hasTrendQuery":bool,"isSocial":bool,"isThirdPartyQuery":bool,"queryNodes":string[]}

RULES:
1. hasReport=true → message contains user's OWN health data to record
2. hasQuery=true → user asks about THEIR OWN health/trends — including declarative query forms ("I want to know about my stress", "I'm curious about my sleep", "tell me how I'm doing")
3. hasTrendQuery=true → user asks about trends, history, or changes over time ("has been", "lately", "recently", "getting better/worse"); only true when hasQuery is also true
4. isSocial=true → ONLY if zero health content (pure greeting/chitchat). If ANY health content → isSocial=false
5. isThirdPartyQuery=true → asking about someone else (family/friend) with NO user health claim. If message also contains user's own health data → isThirdPartyQuery=false, hasReport=true
6. "How are you?" = asking AI → isSocial=true, hasQuery=false
7. "How am I?" = asking about own health → hasQuery=true, isSocial=false
8. queryNodes: ONLY populate when user names specific metrics. Vague queries → []. Max 10.
9. Valid nodes ONLY from: [NODE_LIST]

hasReport+hasQuery CAN both be true. isSocial=true excludes all others.`;

const CLASSIFY_INTENT_SHOTS = [
  { role: 'user',      content: 'I slept 7 hours last night and feel okay.' },
  { role: 'assistant', content: '{"hasReport":true,"hasQuery":false,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: 'How am I doing?' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: "How's my stress and sleep been this week?" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema","sleep_quality"]}' },
  { role: 'user',      content: "I'm exhausted today — how's my sleep looking?" },
  { role: 'assistant', content: '{"hasReport":true,"hasQuery":true,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["sleep_quality"]}' },
  { role: 'user',      content: 'Hey! Good morning!' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":false,"hasTrendQuery":false,"isSocial":true,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: 'How are you doing?' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":false,"hasTrendQuery":false,"isSocial":true,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: 'Actually that stress reading was wrong, ignore it.' },
  { role: 'assistant', content: '{"hasReport":true,"hasQuery":false,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: 'My mom has been really tired lately, what could cause that?' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":false,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":true,"queryNodes":[]}' },
  { role: 'user',      content: "Hey! How's my stress been lately?" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema"]}' },
  { role: 'user',      content: 'What are my stress, sleep, and mood like recently?' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema","sleep_quality","mood"]}' },
  { role: 'user',      content: "That anxiety score was wrong — also how's my anxiety trend?" },
  { role: 'assistant', content: '{"hasReport":true,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema"]}' },
  { role: 'user',      content: 'ok' },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":false,"hasTrendQuery":false,"isSocial":true,"isThirdPartyQuery":false,"queryNodes":[]}' },
  { role: 'user',      content: "Has my stress been getting better lately?" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema"]}' },
  { role: 'user',      content: "How is my stress today?" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema"]}' },
  { role: 'user',      content: "Has my sleep been changing recently?" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["sleep_quality"]}' },
  { role: 'user',      content: "I want to know about my stress" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["stress_ema"]}' },
  { role: 'user',      content: "I'm curious about how I've been sleeping lately" },
  { role: 'assistant', content: '{"hasReport":false,"hasQuery":true,"hasTrendQuery":true,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":["sleep_quality"]}' },
  { role: 'user',      content: "My friend has been anxious and I've also been feeling anxious lately" },
  { role: 'assistant', content: '{"hasReport":true,"hasQuery":false,"hasTrendQuery":false,"isSocial":false,"isThirdPartyQuery":false,"queryNodes":[]}' },
] as const;

const INTENT_FALLBACK: IntentResult = {
  hasReport: true, hasQuery: false, hasTrendQuery: false, isSocial: false, isThirdPartyQuery: false, queryNodes: [],
};

/**
 * Classify user intent using Llama. Always runs on every turn.
 * n_predict=40, temperature=0.0 — output is short structured JSON.
 */
export async function classifyIntent(userText: string): Promise<IntentResult> {
  await ensureNlu();

  const validNodes = new Set(Object.keys(NODE_SCHEMA));
  const nodeList   = Object.keys(NODE_SCHEMA).join(', ');
  const systemPrompt = CLASSIFY_INTENT_SYSTEM_PROMPT.replace('[NODE_LIST]', nodeList);

  // Build prompt: system header + few-shot pairs + actual user turn
  let prompt =
    `<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n` +
    `${systemPrompt}<|eot_id|>`;

  for (const msg of CLASSIFY_INTENT_SHOTS) {
    const role = msg.role === 'user' ? 'user' : 'assistant';
    prompt +=
      `<|start_header_id|>${role}<|end_header_id|>\n\n` +
      `${msg.content}<|eot_id|>`;
  }

  prompt +=
    `<|start_header_id|>user<|end_header_id|>\n\n` +
    `${userText}<|eot_id|>` +
    `<|start_header_id|>assistant<|end_header_id|>\n\n`;

  let raw: string;
  try {
    const out = await _ctx!.completion({
      prompt,
      n_predict:   120,
      temperature: 0.0,
      stop:        ['<|eot_id|>', '<|end_of_text|>'],
    });
    raw = out.text;
  } catch {
    return { ...INTENT_FALLBACK };
  }

  try {
    const cleaned = raw.replace(/```(?:json)?/g, '').trim();
    const start   = cleaned.indexOf('{');
    const end     = cleaned.lastIndexOf('}');
    if (start === -1 || end === -1 || end < start) return { ...INTENT_FALLBACK };

    const parsed = JSON.parse(cleaned.slice(start, end + 1)) as Record<string, unknown>;

    const queryNodes = (Array.isArray(parsed.queryNodes) ? parsed.queryNodes as unknown[] : [])
      .filter((n): n is string => typeof n === 'string' && validNodes.has(n))
      .slice(0, 10);

    return {
      hasReport:         Boolean(parsed.hasReport),
      hasQuery:          Boolean(parsed.hasQuery),
      hasTrendQuery:     Boolean(parsed.hasTrendQuery) && Boolean(parsed.hasQuery),
      isSocial:          Boolean(parsed.isSocial),
      isThirdPartyQuery: Boolean(parsed.isThirdPartyQuery),
      queryNodes,
    };
  } catch {
    return { ...INTENT_FALLBACK };
  }
}

// ── Undo intent detection ──────────────────────────────────────────────────────

const UNDO_SYSTEM_PROMPT = `You detect if a health app user's message contains any intent to undo, correct, or retract something they said in their PREVIOUS message. Answer with only "yes" or "no".

Key rule: "yes" if ANY part of the message corrects or retracts a prior entry — even if the message also contains new unrelated health information.

Examples — pure corrections:
"actually that was wrong, I meant 7 hours" → yes
"wait no, I'm not that stressed" → yes
"I want to correct what I said earlier" → yes
"no wait, my sleep was fine actually" → yes
"forget what I said, I didn't smoke today" → yes
"I made a mistake — it was 8 hours not 4" → yes

Examples — mixed (correction + new info):
"wait I meant 6 hours sleep, also feeling anxious today" → yes
"actually my stress was low not high, and I also had chest pain" → yes
"no that sleep score was wrong, and my mood is better now" → yes

Examples — multi-entity correction:
"actually both were wrong — stress was low and I slept 8 hours" → yes

Examples — negation of prior entry:
"I'm not stressed actually" → yes
"I didn't have chest pain, I was wrong" → yes

Examples — new information only (no correction of prior):
"I slept badly again last night" → no
"I feel a bit better today" → no
"my anxiety is high" → no
"I exercised this morning" → no
"I had 3 beers" → no
"I didn't exercise today" → no
"I actually exercised this morning" → no
"I actually slept well last night" → no
"I feel stressed, and I can't explain to anyone" → no
"I feel extremely stressed" → no
"I can't seem to relax lately" → no
"I feel overwhelmed" → no
"I don't feel well today" → no
"I haven't been sleeping well" → no

Examples — soft/hedged corrections (still yes):
"I don't think my sleep was that bad actually" → yes
"I may have overstated my stress earlier" → yes
"looking back I think I exaggerated the anxiety" → yes`;

// Keyword gate: words that can only appear in a correction/undo message.
// Plain health reports never contain these. If none present → skip model entirely.
const UNDO_KEYWORDS = [
  'actually', 'wait no', 'i meant', 'i mean ', 'was wrong', 'were wrong',
  'that was', 'that\'s wrong', 'thats wrong', 'not true', 'mistake',
  'wrong,', 'wrong.', 'wrong!', 'incorrect', 'disregard', 'ignore that',
  'forget what', 'undo', 'take back', 'retract', 'correct that',
  'i lied', 'i exaggerated', 'i overstated', 'overstated',
  'looking back', 'on second thought', 'i think i was',
  'i said wrong', 'i told wrong', 'that info was',
];

function hasUndoSignal(text: string): boolean {
  const lower = text.toLowerCase();
  return UNDO_KEYWORDS.some(kw => lower.includes(kw));
}

/** Returns true if the user's message signals intent to undo or correct a previous entry. */
export async function detectUndoIntent(userText: string): Promise<boolean> {
  // Fast gate: no correction keyword → definitely not an undo. Skip model entirely.
  if (!hasUndoSignal(userText)) return false;

  await ensureNlu();
  const prompt =
    `<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n` +
    `${UNDO_SYSTEM_PROMPT}<|eot_id|>` +
    `<|start_header_id|>user<|end_header_id|>\n\n` +
    `${userText}<|eot_id|>` +
    `<|start_header_id|>assistant<|end_header_id|>\n\n`;
  try {
    const out = await _ctx!.completion({
      prompt,
      n_predict:   3,
      temperature: 0.0,
      stop:        ['<|eot_id|>', '\n'],
    });
    return out.text.toLowerCase().trimStart().startsWith('yes');
  } catch {
    return false;
  }
}
