"""
sync_configs.py
Syncs configs/ → mobile assets after any retraining pipeline run.

Actions:
  1. Copy 5 JSON files from configs/ to mobile/src/assets/ (underscore → dash rename)
  2. Regenerate populationNormStats.ts from population_norm_stats.json

Run:  python Codebase/backend/sync_configs.py
"""
import json
import shutil
from pathlib import Path

ROOT     = Path(__file__).parent.parent.parent
CONFIGS  = ROOT / 'configs'
ASSETS   = ROOT / 'Codebase' / 'mobile' / 'src' / 'assets'
NORM_TS  = ROOT / 'Codebase' / 'mobile' / 'src' / 'core' / 'sensorCollectors' / 'populationNormStats.ts'

# configs/<src> → assets/<dst>
JSON_COPY_MAP = {
    'feature_node_config.json':        'feature-node-config.json',
    'dbn_structure.json':              'dbn-structure.json',
    'cpd_tables.json':                 'cpd-tables.json',
    'source_column_descriptions.json': 'source-column-descriptions.json',
    'column_question_map.json':        'column-question-map.json',
}

# ── Helpers ────────────────────────────────────────────────────────────────────

def copy_json_files() -> None:
    for src_name, dst_name in JSON_COPY_MAP.items():
        src = CONFIGS / src_name
        dst = ASSETS  / dst_name
        if not src.exists():
            print(f'  SKIP  {src_name} (not found in configs/)')
            continue
        shutil.copy2(src, dst)
        print(f'  COPY  {src_name}  ->  assets/{dst_name}')


def regenerate_norm_ts() -> None:
    src = CONFIGS / 'population_norm_stats.json'
    if not src.exists():
        print('  SKIP  populationNormStats.ts  (population_norm_stats.json not found)')
        return

    stats: dict = json.loads(src.read_text(encoding='utf-8'))

    # Align col names for readability
    max_len   = max(len(col) for col in stats)
    col_lines = []
    for col, v in stats.items():
        pad = ' ' * (max_len - len(col))
        col_lines.append(f'  {col}:{pad} {{ mean: {v["mean"]},  std: {v["std"]}  }},')
    entries = '\n'.join(col_lines)

    ts = (
        '/**\n'
        ' * populationNormStats.ts\n'
        ' *\n'
        ' * Auto-generated from configs/population_norm_stats.json — do not edit manually.\n'
        ' *\n'
        ' * Population-level mean and std for each sensor column used by the DBN.\n'
        ' * These values are baked in at build time so Metro bundler does not need\n'
        ' * access to the configs/ directory (which lives outside the mobile source tree).\n'
        ' *\n'
        ' * Used by sensor collectors to compute population z-scores for discretization.\n'
        ' */\n'
        '\n'
        '// ── Types ─────────────────────────────────────────────────────────────────────\n'
        '\n'
        'export interface ColStats {\n'
        '  mean: number;\n'
        '  std:  number;\n'
        '}\n'
        '\n'
        '// ── Population norm stats ─────────────────────────────────────────────────────\n'
        '\n'
        '/**\n'
        ' * Population z-score parameters for all sensor columns handled by the\n'
        ' * screen-usage and communication collectors.\n'
        ' * source: configs/population_norm_stats.json (generated by DBN training pipeline)\n'
        ' */\n'
        'export const POPULATION_NORM_STATS: Record<string, ColStats> = {\n'
        f'{entries}\n'
        '};\n'
        '\n'
        '// ── Shared discretization helper ──────────────────────────────────────────────\n'
        '\n'
        '/**\n'
        ' * Classify `value` into a named state using an ordered list of bin edges.\n'
        ' *\n'
        ' * Matches pandas pd.cut(right=True, include_lowest=True):\n'
        " *   bins = (-inf, binEdges[0]], (binEdges[0], binEdges[1]], ..., (binEdges[last], +inf)\n"
        ' *\n'
        ' * For population z-score cols the bin_edges are in z-score space.\n'
        ' * For clinical-threshold cols (activity) the bin_edges are in ratio space.\n'
        ' *\n'
        ' * @param value       - the value to classify (z-score or raw ratio)\n'
        ' * @param binEdges    - sorted ascending boundary values (length = stateLabels.length - 1)\n'
        ' * @param stateLabels - state names, one more than binEdges\n'
        ' * @returns           the matched state label\n'
        ' */\n'
        'export function discretizeByEdges(\n'
        '  value:       number,\n'
        '  binEdges:    number[],\n'
        '  stateLabels: string[],\n'
        '): string {\n'
        '  for (let i = 0; i < binEdges.length; i++) {\n'
        '    if (value <= binEdges[i]) return stateLabels[i];\n'
        '  }\n'
        '  return stateLabels[stateLabels.length - 1];\n'
        '}\n'
    )

    NORM_TS.write_text(ts, encoding='utf-8')
    print(f'  REGEN populationNormStats.ts  ({len(stats)} cols)')


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    print('sync_configs: configs/ -> mobile assets')
    copy_json_files()
    regenerate_norm_ts()
    print('Done.')


if __name__ == '__main__':
    main()
